/* EpicDash UX r27 — contextual diagnostics with digital square-wave trigger rendering and live settings. */
(function(){
'use strict';
const tools=[
  {id:'faults',icon:'◉',title:'Fault Codes',sub:'Display and ECU-reported faults'},
  {id:'sensors',icon:'◎',title:'Sensor Health',sub:'Live plausibility and trends'},
  {id:'trigger',icon:'◴',title:'Trigger / Sync',sub:'Crank, cam and combined diagnostics'},
  {id:'communications',icon:'⌁',title:'Communications',sub:'USB transport and latency'},
  {id:'power',icon:'ϟ',title:'Power & Grounds',sub:'Voltage and supply checks'},
  {id:'network',icon:'≋',title:'CAN / Serial',sub:'Read-only bus monitor'},
  {id:'ecu',icon:'ⓘ',title:'ECU Info',sub:'Hardware and firmware identity'},
  {id:'actuators',icon:'⚙',title:'Actuator Tests',sub:'Locked by read-only policy',disabled:true}
];
let activeTool='faults',search='',triggerTab='combo',bound=false,lastRefresh=0,lastSample=0,lastFaultKey='',lastConnection='',events=[],trends={batt:[],sync:[],tooth:[],rpm:[],clt:[],afr:[],fuelDelta:[]},tests=[],nativeCache={},sessionStart=Date.now(),bottomVisible=true,diagTrendSeconds=60,diagVerbosity='normal',diagRawValues=false;
const maxEvents=80,DIAG_BOTTOM_KEY='epicdashUX.diagBottom.v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isNum=v=>Number.isFinite(Number(v));
const n=(v,d=1)=>isNum(v)?Number(v).toFixed(d):'—';
function dPresent(kind,v){try{return window.SettingsUX?.present?.(kind,v)||{text:n(v,1),unit:'',raw:v}}catch(_){return{text:n(v,1),unit:'',raw:v}}}
function diagValue(name,v,unit){if(name.includes('Coolant')||name.includes('Intake Air'))return dPresent('temperature',v);if(name==='MAP'||name.includes('Fuel ΔP'))return dPresent('pressureKpa',v);if(name.includes('Fuel Pressure')||name.includes('Oil Pressure'))return dPresent('pressureBar',v);if(name.includes('AFR'))return dPresent('afr',v);if(name.includes('Battery'))return dPresent('voltage',v);return{text:isNum(v)?n(v,unit==='V'||unit==='bar'||unit==='AFR'?1:0):'—',unit,raw:v}}
const nowTime=()=>new Date().toLocaleTimeString([],{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});
function stateRef(){try{return state}catch(_){return {}}}
function appMode(){try{return demo?'DEMO':liveSeen?'LIVE':'OFFLINE'}catch(_){return 'OFFLINE'}}
function nativeDiagnostics(){try{return JSON.parse(window.EpicDashAndroid?.getDiagnosticsJson?.()||'{}')}catch(_){return {}}}
function loadPrefs(){try{const v=localStorage.getItem(DIAG_BOTTOM_KEY);if(v!==null)bottomVisible=v!=='false'}catch(_){}}
function savePrefs(){try{localStorage.setItem(DIAG_BOTTOM_KEY,String(bottomVisible))}catch(_){}}
function addEvent(type,message,severity='info'){const last=events[events.length-1];if(last&&last.type===type&&last.message===message&&Date.now()-last.ts<1500)return;events.push({ts:Date.now(),time:nowTime(),type,message,severity});if(events.length>maxEvents)events.splice(0,events.length-maxEvents)}
function sensor(name,value,unit,min,max,judge,expected){const v=Number(value),kind=Number.isFinite(v)?judge(v):'warn';return{name,value:Number.isFinite(v)?v:NaN,unit,min,max,kind,status:Number.isFinite(v)?kind==='ok'?'OK':kind==='warn'?'CHECK':'FAULT':'NO DATA',expected}}
function sensorRows(){const s=stateRef(),running=Number(s.rpm)>400;return [
  sensor('Coolant Temp (CLT)',s.clt,'°C',-40,115,v=>v>105?'bad':v>98?'warn':'ok','Expected −40…115 °C'),
  sensor('Intake Air Temp (IAT)',s.iat,'°C',-40,100,v=>v>65?'bad':v>50?'warn':'ok','Expected −40…100 °C'),
  sensor('Throttle Position (TPS)',s.tps,'%',0,100,v=>v<-.5||v>100.5?'bad':'ok','Expected 0…100 %'),
  sensor('MAP',s.map,'kPa',10,260,v=>v<10||v>260?'bad':'ok','Expected 10…260 kPa'),
  sensor('Battery Voltage',s.batt,'V',11,15.5,v=>v<11.5||v>15.2?'bad':v<12.2||v>14.8?'warn':'ok','Expected 11.0…15.5 V'),
  sensor('AFR Gas Scale',s.afr,'AFR',9,20,v=>v<9||v>20?'bad':v>16&&Number(s.map)>100?'warn':'ok','Expected display range 9…20'),
  sensor('Fuel Pressure',isNum(s.fuelPressure)?Number(s.fuelPressure)/100:NaN,'bar',2,6,v=>v<2?'bad':v<2.5||v>5?'warn':'ok','Expected 2.5…6.0 bar'),
  sensor('Fuel ΔP',s.fuelDelta,'kPa',150,450,v=>v<180?'bad':v<240?'warn':'ok','Expected approximately 300 kPa'),
  sensor('Oil Pressure',s.oilPressure,'bar',0,10,v=>running&&v<.8?'bad':running&&v<1.2?'warn':'ok',running?'Running-engine minimum >1.0 bar':'Engine not running threshold relaxed'),
  sensor('Knock Retard',s.knockRetard,'°',0,12,v=>v>4?'bad':v>1?'warn':'ok','Expected 0° during normal operation')
]}
function faults(){const s=stateRef(),out=[];const push=(code,title,detail,kind='warn')=>out.push({code,title,detail,kind});
 if(Number(s.errorCount)>0)push('APP-ECU',`${Math.round(Number(s.errorCount))} ECU error state${Number(s.errorCount)===1?'':'s'} reported`,'The runtime channel indicates one or more ECU errors. Open ECU-native diagnostics for exact codes.','bad');
 if(isNum(s.batt)&&Number(s.batt)<11.5){const v=dPresent('voltage',s.batt),lim=dPresent('voltage',11.5);push('PWR-LOW','System voltage low',`${v.text} ${v.unit} is below the ${lim.text} ${lim.unit} display threshold.`,'bad')}
 if(Number(s.rpm)>400&&isNum(s.oilPressure)&&Number(s.oilPressure)<1){const v=dPresent('pressureBar',s.oilPressure);push('OIL-LOW','Oil pressure low while running',`${v.text} ${v.unit} at ${Math.round(Number(s.rpm))} rpm.`,'bad')}
 if(isNum(s.fuelDelta)&&Number(s.fuelDelta)<200){const v=dPresent('pressureKpa',s.fuelDelta),exp=dPresent('pressureKpa',300);push('FUEL-DP','Fuel pressure differential low',`${v.text} ${v.unit}; expected approximately ${exp.text} ${exp.unit}.`,'bad')}
 if(isNum(s.clt)&&Number(s.clt)>105){const v=dPresent('temperature',s.clt),lim=dPresent('temperature',105);push('CLT-HOT','Coolant temperature high',`${v.text} ${v.unit} exceeds the ${lim.text} ${lim.unit} warning threshold.`,'warn')}
 if(isNum(s.afr)&&isNum(s.map)&&Number(s.map)>100&&Number(s.afr)>16){const a=dPresent('afr',s.afr),m=dPresent('pressureKpa',s.map);push('AFR-LEAN','Lean mixture under load',`${a.text} ${a.unit} at ${m.text} ${m.unit}.`,'bad')}
 if(Number(s.syncOk)===0)push('SYNC-LOSS','Engine synchronization lost','Crank/cam synchronization channel reports an invalid state.','bad');
 if(isNum(s.knockRetard)&&Number(s.knockRetard)>3)push('KNOCK','High knock retard',`${n(s.knockRetard,1)}° retard is active.`,'warn');return out}
function checkFaultEvents(){const list=faults(),key=list.map(x=>x.code).sort().join('|');if(key!==lastFaultKey){if(key)addEvent('FAULT',`${list.length} diagnostic condition${list.length===1?'':'s'} active`,list.some(x=>x.kind==='bad')?'bad':'warn');else if(lastFaultKey)addEvent('INFO','Diagnostic conditions returned to normal','info');lastFaultKey=key}}
function connectionState(){let connected=false,p='OFFLINE',hz=0;try{connected=typeof signalAvailable==='function'?signalAvailable():(!!liveSeen||!!demo);p=String(phase||appMode());hz=Number(measuredHz)||0}catch(_){}const mode=appMode();return{connected,mode,phase:p.replaceAll('_',' ').toUpperCase(),hz}}
function checkConnectionEvent(){const c=connectionState(),key=`${c.connected}:${c.phase}`;if(key!==lastConnection){addEvent('COMM',c.connected?`${c.mode} diagnostics source active`:`Connection state: ${c.phase}`,c.connected?'info':'warn');lastConnection=key}}
function sampleTrends(){const s=stateRef(),c=connectionState();if(!c.connected)return;const push=(key,v)=>{if(!isNum(v))return;trends[key].push(Number(v));const maxTrend=Math.max(20,Math.round(diagTrendSeconds*1000/450));if(trends[key].length>maxTrend)trends[key].splice(0,trends[key].length-maxTrend)};push('batt',s.batt);push('sync',Number(s.syncOk)===0?1:0);push('rpm',s.rpm);let demoOn=false;try{demoOn=!!demo}catch(_){}push('tooth',demoOn?2.1+Math.sin(Date.now()/470)*1.25:Math.max(0,Math.min(15,100/(c.hz||20))));push('clt',s.clt);push('afr',s.afr);push('fuelDelta',s.fuelDelta)}
function spark(values,kind='cyan'){const a=values.length?values:[0,0],min=Math.min(...a),max=Math.max(...a),pts=a.map((v,i)=>`${i*200/Math.max(1,a.length-1)},${62-(max>min?(v-min)/(max-min):.5)*52}`).join(' '),color=kind==='green'?'#82d600':kind==='amber'?'#ff9800':kind==='red'?'#ff3728':'#00bdf4';return `<svg viewBox="0 0 200 68" preserveAspectRatio="none"><path d="M0 17H200M0 34H200M0 51H200M50 0V68M100 0V68M150 0V68" stroke="#102936" stroke-width="1"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="1.7"/></svg>`}
function summaryTiles(){const s=stateRef(),c=connectionState(),fs=faults(),sync=Number(s.syncOk)!==0,bat=dPresent('voltage',s.batt),clt=dPresent('temperature',s.clt),iat=dPresent('temperature',s.iat),map=dPresent('pressureKpa',s.map),afr=dPresent('afr',s.afr);return [
  ['▣',c.connected?c.mode:'OFFLINE',c.phase,c.connected?'ok':'warn'],['◴',sync?'SYNCHRONIZED':'SYNC LOST',sync?'0 active loss':'Check trigger',sync?'ok':'bad'],['▤',`${bat.text} ${bat.unit}`,isNum(s.batt)&&Number(s.batt)>=12.2&&Number(s.batt)<=14.8?'Good':'Check',isNum(s.batt)&&Number(s.batt)>=11.5&&Number(s.batt)<=15.2?'ok':'bad'],['♨',`${clt.text} ${clt.unit}`,isNum(s.clt)&&Number(s.clt)<98?'Normal':'Hot',isNum(s.clt)&&Number(s.clt)<98?'ok':Number(s.clt)<105?'warn':'bad'],['♨',`${iat.text} ${iat.unit}`,isNum(s.iat)&&Number(s.iat)<50?'Normal':'Hot',isNum(s.iat)&&Number(s.iat)<50?'ok':'warn'],['◴',`${n(s.tps,1)} %`,'Throttle',isNum(s.tps)?'ok':'warn'],['◉',`${map.text} ${map.unit}`,'Engine load',isNum(s.map)?'ok':'warn'],['λ',afr.text,afr.unit,isNum(s.afr)?'ok':'warn'],['!',String(fs.length),fs.length?'Conditions':'No active faults',fs.some(x=>x.kind==='bad')?'bad':fs.length?'warn':'ok']
]}
function renderSummary(){const box=document.getElementById('diagV2Summary');if(!box)return;box.innerHTML=summaryTiles().map(x=>`<section class="pCard diagV2SummaryTile ${x[3]}"><span class="diagV2SummaryIcon">${x[0]}</span><div><b>${esc(x[1])}</b><small>${esc(x[2])}</small></div></section>`).join('')}
function toolCount(id){if(id==='faults')return faults().length;if(id==='sensors')return sensorRows().filter(x=>x.kind!=='ok').length;return 0}
function renderNav(){const nav=document.getElementById('diagV2Nav');if(!nav)return;const scroll=nav.scrollTop,q=search.trim().toLowerCase(),filtered=tools.filter(t=>!q||`${t.title} ${t.sub}`.toLowerCase().includes(q));nav.innerHTML=filtered.map(t=>{const count=toolCount(t.id);return `<div class="diagV2NavItem ${activeTool===t.id?'active':''} ${t.disabled?'disabled':''}" data-diag-action="tool" data-tool="${t.id}"><span class="diagV2NavIcon">${t.icon}</span><span><strong>${esc(t.title)}</strong><small>${esc(t.sub)}</small></span>${count?`<span class="diagV2Badge">${count}</span>`:''}</div>`}).join('')||'<div class="diagV2Empty"><b>No matching tools</b></div>';nav.scrollTop=scroll}
function diagPhoneMode(){const v=document.body?.dataset?.uxViewport||'';return v==='phone-portrait'||v==='phone-landscape'}
function head(title,subtitle='',actions=''){const long=String(title||'').length>28?' longTitle':'';return `<div class="diagV2MainHead${long}"><b>${esc(title)}</b>${subtitle?`<small>${esc(subtitle)}</small>`:''}<span class="spacer"></span>${actions}</div>`}
function faultView(){const list=faults();return head('FAULT CODES & DISPLAY CONDITIONS','Read-only; no clear command is exposed',`<button class="pButton active" data-diag-action="refresh">REFRESH</button><button class="pButton" data-diag-action="copyReport">COPY REPORT</button>`)+`<div class="diagV2MainBody">${list.length?list.map(f=>`<div class="diagV2FaultCard ${f.kind}"><div class="diagV2FaultCode">${esc(f.code)}</div><div class="diagV2FaultText"><b>${esc(f.title)}</b><small>${esc(f.detail)}</small></div><div class="diagV2FaultState ${f.kind}">${f.kind==='bad'?'CRITICAL':'WARNING'}</div></div>`).join(''):`<div class="diagV2Empty"><div class="diagV2EmptyIcon">✓</div><b>No active diagnostic conditions</b><small>No display-derived fault is active at the current sample.</small></div>`}<div class="diagV2Panel" style="margin-top:7px"><div class="diagV2PanelHead">Interpretation boundary</div><div class="diagV2PanelBody" style="font-size:8px;color:#788b94;line-height:1.5">The conditions above are derived from available runtime channels and app warning thresholds. They are not a replacement for firmware-native DTC memory. When the native bridge exposes exact ECU codes, those can be shown here without enabling clear-code or write commands.</div></div></div>`}
function diagnosticExpected(x){
 if(x.name==='Oil Pressure'&&!Number(stateRef().rpm||0))return'Engine not running threshold relaxed';
 const lo=diagValue(x.name,x.min,x.unit),hi=diagValue(x.name,x.max,x.unit);
 if(x.name==='Fuel ΔP'){const target=diagValue(x.name,300,x.unit);return`Expected approximately ${target.text} ${target.unit}`}
 if(x.name==='Oil Pressure'){const target=diagValue(x.name,1,x.unit);return`Running-engine minimum >${target.text} ${target.unit}`}
 if(Number.isFinite(x.min)&&Number.isFinite(x.max))return`Expected ${lo.text}…${hi.text} ${hi.unit}`;
 return x.expected||'';
}
function sensorView(){return head('SENSOR HEALTH','Live plausibility and status; detailed trends are in the contextual lower panel',`<button class="pButton active" data-diag-action="runChecks">RUN DISPLAY CHECKS</button>`)+`<div class="diagV2MainBody"><div class="diagV2SensorList">${sensorRows().map(x=>{const d=diagValue(x.name,x.value,x.unit),raw=diagRawValues&&isNum(x.value)?`<em class="diagRawInline">raw ${n(x.value,3)} ${esc(x.unit)}</em>`:'';return`<div class="diagV2Sensor ${x.kind}"><strong>${esc(x.name)}</strong><b>${esc(d.text)} ${esc(d.unit)}</b><small>${diagVerbosity==='compact'?'':esc(diagnosticExpected(x))}</small>${raw}<span class="diagState">${esc(x.status)}</span></div>`}).join('')}</div></div>`}
function triggerPhase(){const rpm=Math.max(0,Number(stateRef().rpm)||0),running=rpm>50,speed=running?Math.max(.15,Math.min(3.4,rpm/900)):.12;return{rpm,running,phase:(Date.now()/1000*speed)%1}}
function squareToothPath(period,teeth,baseline,high,phasePx,missing=0,duty=.46){
  let d='',start=-period-phasePx,step=period/teeth;
  for(let base=start;base<760;base+=period){
    d+=`${d?' M':'M'}${base.toFixed(1)} ${baseline.toFixed(1)}`;
    for(let i=0;i<teeth;i++){
      const x=base+i*step,next=x+step;
      if(i<teeth-missing){const fall=x+step*Math.max(.12,Math.min(.88,duty));d+=` L${x.toFixed(1)} ${baseline.toFixed(1)} L${x.toFixed(1)} ${high.toFixed(1)} L${fall.toFixed(1)} ${high.toFixed(1)} L${fall.toFixed(1)} ${baseline.toFixed(1)} L${next.toFixed(1)} ${baseline.toFixed(1)}`}
      else d+=` L${next.toFixed(1)} ${baseline.toFixed(1)}`;
    }
  }
  return d;
}
function squareCamPath(period,baseline,high,phasePx){
  let d='',start=-period-phasePx;
  for(let base=start;base<760;base+=period){
    const rise=base+period*.10,fall=base+period*.36,end=base+period;
    d+=`${d?' M':'M'}${base.toFixed(1)} ${baseline.toFixed(1)} L${rise.toFixed(1)} ${baseline.toFixed(1)} L${rise.toFixed(1)} ${high.toFixed(1)} L${fall.toFixed(1)} ${high.toFixed(1)} L${fall.toFixed(1)} ${baseline.toFixed(1)} L${end.toFixed(1)} ${baseline.toFixed(1)}`;
  }
  return d;
}
function triggerWave(kind='combo'){
  const s=stateRef(),good=Number(s.syncOk)!==0,t=triggerPhase(),phasePx=t.phase*480,stroke=good?'#00bdf4':'#ff3728',cursor=24+t.phase*672;
  const grid='<path d="M0 36H720M0 72H720M0 108H720M0 144H720M90 0V180M180 0V180M270 0V180M360 0V180M450 0V180M540 0V180M630 0V180" stroke="#102936" stroke-width="1"/>';
  const crankBase=kind==='combo'?72:118,crankHigh=kind==='combo'?28:46;
  const camBase=kind==='combo'?154:118,camHigh=kind==='combo'?112:46;
  const crank=`<path d="${squareToothPath(480,60,crankBase,crankHigh,phasePx,2,.48)}" fill="none" stroke="${stroke}" stroke-width="0.82" vector-effect="non-scaling-stroke" stroke-linecap="square" stroke-linejoin="miter"/>`;
  const cam=`<path d="${squareCamPath(480,camBase,camHigh,phasePx)}" fill="none" stroke="${good?'#82d600':'#ff3728'}" stroke-width="1.05" vector-effect="non-scaling-stroke" stroke-linecap="square" stroke-linejoin="miter"/>`;
  const body=kind==='crank'?crank:kind==='cam'?cam:`${crank}${cam}`;
  const labels=kind==='combo'?'<text x="12" y="18" fill="#78909a" font-size="10">CRANK 60−2 DIGITAL</text><text x="12" y="102" fill="#78909a" font-size="10">CAM DIGITAL</text>':`<text x="12" y="18" fill="#78909a" font-size="10">${kind==='crank'?'60−2 crank square wave':'Cam square wave'}</text>`;
  return `<svg viewBox="0 0 720 180" preserveAspectRatio="none">${grid}${body}<line x1="${cursor}" y1="0" x2="${cursor}" y2="180" stroke="#e7f9ff" stroke-width="1" opacity=".70"/>${labels}<text x="708" y="17" fill="#78909a" font-size="9" text-anchor="end">${Math.round(t.rpm)} rpm • ~5 Hz screen update • ${nowTime()}</text>${!t.running?'<text x="360" y="92" fill="#ff9800" font-size="12" text-anchor="middle">NO ROTATION — ANIMATED SQUARE-WAVE PREVIEW</text>':''}</svg>`;
}
function triggerView(){const c=connectionState();if(!c.connected)return head('TRIGGER / SYNC DIAGNOSTICS','Crank and cam rendering is paused until DEMO or live ECU data is available',`<div class="diagV2TriggerTabs"><button class="${triggerTab==='crank'?'active':''}" data-diag-action="triggerTab" data-value="crank">CRANK</button><button class="${triggerTab==='cam'?'active':''}" data-diag-action="triggerTab" data-value="cam">CAM</button><button class="${triggerTab==='combo'?'active':''}" data-diag-action="triggerTab" data-value="combo">COMBO</button></div>`)+`<div class="diagV2MainBody"><div class="diagV2Wave noSignal"><div><b>NO SIGNAL</b><span>Crank and cam rendering stopped</span></div></div><div class="diagV2Stats"><div class="diagV2Stat"><h4>SYNC STATE</h4><div><span>State</span><b>—</b></div><div><span>Loss count</span><b>—</b></div><div><span>Update</span><b>PAUSED</b></div></div><div class="diagV2Stat"><h4>TOOTH ERROR</h4><div><span>Current</span><b>—</b></div><div><span>Expected</span><b>&lt; 7.5 %</b></div><div><span>Pattern</span><b>60−2</b></div></div><div class="diagV2Stat"><h4>TRIGGER STATUS</h4><div><span>Crank</span><b>—</b></div><div><span>Cam</span><b>—</b></div><div><span>Visual source</span><b>PAUSED</b></div></div></div></div>`;const s=stateRef(),good=Number(s.syncOk)!==0,tooth=trends.tooth.length?trends.tooth[trends.tooth.length-1]:0;return head('TRIGGER / SYNC DIAGNOSTICS','Animated from RPM and sync state; not a raw tooth-logger capture',`<div class="diagV2TriggerTabs"><button class="${triggerTab==='crank'?'active':''}" data-diag-action="triggerTab" data-value="crank">CRANK</button><button class="${triggerTab==='cam'?'active':''}" data-diag-action="triggerTab" data-value="cam">CAM</button><button class="${triggerTab==='combo'?'active':''}" data-diag-action="triggerTab" data-value="combo">COMBO</button></div>`)+`<div class="diagV2MainBody"><div class="diagV2Wave ${triggerTab==='combo'?'combo':''}">${triggerWave(triggerTab)}</div><div class="diagV2Stats"><div class="diagV2Stat"><h4>SYNC STATE</h4><div><span>State</span><b class="${good?'ok':'bad'}">${good?'LOCKED':'LOST'}</b></div><div><span>Loss count</span><b>${good?'0':'1+'}</b></div><div><span>Update</span><b class="ok">LIVE</b></div></div><div class="diagV2Stat"><h4>TOOTH ERROR</h4><div><span>Current</span><b class="${tooth<7.5?'ok':'warn'}">${n(tooth,1)} %</b></div><div><span>Expected</span><b>&lt; 7.5 %</b></div><div><span>Pattern</span><b>60−2</b></div></div><div class="diagV2Stat"><h4>TRIGGER STATUS</h4><div><span>Crank</span><b class="${good?'ok':'bad'}">${good?'GOOD':'CHECK'}</b></div><div><span>Cam</span><b class="${good?'ok':'bad'}">${good?'GOOD':'CHECK'}</b></div><div><span>Visual source</span><b>RPM/SYNC</b></div></div></div></div>`}
function flatten(obj,prefix='',out=[]){if(!obj||typeof obj!=='object'||out.length>40)return out;for(const [k,v] of Object.entries(obj)){const key=prefix?`${prefix}.${k}`:k;if(v&&typeof v==='object'&&!Array.isArray(v))flatten(v,key,out);else out.push([key,Array.isArray(v)?JSON.stringify(v):String(v)])}return out}
function commView(kind='communications'){const c=connectionState(),native=nativeCache,flat=flatten(native),base=kind==='network'?[['Mode',c.mode],['Transport',appMode()==='DEMO'?'Demo simulation':'USB OTG'],['Protocol','EpicEFI read-only'],['Poll target','20 Hz'],['Measured callback',c.hz?`${n(c.hz,1)} Hz`:'—'],['CAN writes','Disabled'],['Serial writes','Disabled'],['Errors',String(stateRef().errorCount||0)]]:[['Connection',c.connected?'Connected':'Offline'],['Phase',c.phase],['Source',c.mode],['Measured rate',c.hz?`${n(c.hz,1)} Hz`:'—'],['USB path',appMode()==='DEMO'?'Simulated':'Native bridge'],['ECU writes','Disabled'],['Timeout policy','Read-only reconnect'],['Session uptime',`${Math.floor((Date.now()-sessionStart)/1000)} s`]];return head(kind==='network'?'CAN / SERIAL MONITOR':'COMMUNICATIONS / ECU LINK','Read-only transport diagnostics',`<button class="pButton active" data-diag-action="refresh">REFRESH NATIVE</button>`)+`<div class="diagV2MainBody"><div class="diagV2InfoGrid">${base.map(x=>`<div class="diagV2InfoLine"><span>${esc(x[0])}</span><b class="${String(x[1]).match(/Connected|Disabled|DEMO|LIVE|OK/i)?'ok':''}">${esc(x[1])}</b></div>`).join('')}</div><div class="diagV2Panel" style="margin-top:7px"><div class="diagV2PanelHead">Native bridge diagnostics <span class="spacer"></span><span>${flat.length} fields</span></div><pre class="diagV2Raw">${esc(flat.length?flat.map(x=>`${x[0]}: ${x[1]}`).join('\n'):'Native diagnostic bridge returned no structured fields in this wrapper.')}</pre></div></div>`}
function checks(){const s=stateRef(),c=connectionState(),rows=sensorRows(),bad=rows.filter(x=>x.kind==='bad').length,warn=rows.filter(x=>x.kind==='warn').length;return [
  {name:'Power & Ground',kind:isNum(s.batt)&&Number(s.batt)>=11.5&&Number(s.batt)<=15.2?'ok':'bad',detail:`${n(s.batt,1)} V available`},
  {name:'Sensor Plausibility',kind:bad?'bad':warn?'warn':'ok',detail:`${bad} fault • ${warn} check`},
  {name:'Trigger Signal',kind:Number(s.syncOk)!==0?'ok':'bad',detail:Number(s.syncOk)!==0?'Synchronized':'Sync invalid'},
  {name:'Communications',kind:c.connected?'ok':'warn',detail:c.phase},
  {name:'Read-only Safety',kind:'ok',detail:'Write commands absent'},
  {name:'App Runtime',kind:'ok',detail:`${appMode()} • ${Math.floor((Date.now()-sessionStart)/1000)} s`}
]}
function powerView(){const s=stateRef(),list=checks();return head('POWER & GROUNDS','Display-only electrical plausibility checks',`<button class="pButton active" data-diag-action="runChecks">RUN CHECKS</button>`)+`<div class="diagV2MainBody"><div class="diagV2Checks">${list.map(x=>`<div class="diagV2Check ${x.kind}"><span class="diagV2CheckIcon">${x.kind==='ok'?'✓':x.kind==='warn'?'!':'×'}</span><span><strong>${esc(x.name)}</strong><small>${esc(x.detail)}</small></span><b>${x.kind.toUpperCase()}</b></div>`).join('')}</div><div class="diagV2Grid2" style="min-height:0;margin-top:7px"><div class="diagV2Panel"><div class="diagV2PanelHead">Battery trend</div><div class="diagV2PanelBody" style="height:150px">${spark(trends.batt,isNum(s.batt)&&Number(s.batt)>=11.5?'cyan':'red')}</div></div><div class="diagV2Panel"><div class="diagV2PanelHead">Electrical notes</div><div class="diagV2PanelBody" style="font-size:8px;color:#81949d;line-height:1.55">These checks can identify implausible voltage and obvious runtime-channel faults. They cannot measure voltage drop at grounds, alternator ripple, connector resistance, or sensor-reference stability without additional hardware channels.</div></div></div></div>`}
function ecuView(){let d={};try{d=appDiagnosticsObject()}catch(_){}const c=connectionState(),items=[['Application','EpicDash UX'],['Version',d.version||'0.12.15-ux-resp17'],['Package','com.buttonbox.ble.ul'],['Mode',c.mode],['ECU profile','Mega144H7'],['Firmware definition','rusEFI master.2026.05.24'],['Tune baseline','CurrentTune.msq'],['Tune settings',String(d.tuneSettings||5960)],['Table definitions','123'],['ECU access','Read-only'],['Tune writes','Not implemented'],['Output control','Not implemented']];return head('ECU / APPLICATION INFORMATION','Identity and safety boundary',`<button class="pButton" data-diag-action="copyReport">COPY FULL REPORT</button>`)+`<div class="diagV2MainBody"><div class="diagV2InfoGrid">${items.map(x=>`<div class="diagV2InfoLine"><span>${esc(x[0])}</span><b class="${String(x[1]).match(/Read-only|Not implemented/i)?'ok':''}">${esc(x[1])}</b></div>`).join('')}</div><pre class="diagV2Raw">${esc(JSON.stringify(d,null,2))}</pre></div>`}
function actuatorView(){const names=['Cooling fan','Fuel-pump relay','Injector test','Ignition test','Boost solenoid','Idle-air valve','EGR solenoid','Main relay'];return head('ACTUATOR / OUTPUT TESTS','Intentionally unavailable in EpicDash UX')+`<div class="diagV2MainBody"><div class="diagV2ActuatorLock"><div class="diagV2LockBox"><div class="diagV2LockIcon">🔒</div><h3>READ-ONLY POLICY LOCK</h3><p>EpicDash UX may display output states, but it does not send output-test, relay-cycle, injector-test, ignition-test, virtual-input, tune-write or burn commands to the ECU.</p><div class="diagV2LockList">${names.map(x=>`<div>${esc(x)}<b>DISABLED</b></div>`).join('')}</div></div></div></div>`}
function mainContent(){switch(activeTool){case'sensors':return sensorView();case'trigger':return triggerView();case'communications':return commView('communications');case'power':return powerView();case'network':return commView('network');case'ecu':return ecuView();case'actuators':return actuatorView();default:return faultView()}}
function renderMain(){const box=document.getElementById('diagV2Main');if(!box)return;const body=box.querySelector('.diagV2MainBody'),scroll=body?body.scrollTop:0;box.innerHTML=mainContent();const next=box.querySelector('.diagV2MainBody');if(next)next.scrollTop=scroll}
function eventRows(filter=null){const list=(filter?events.filter(filter):events).slice(-12).reverse();return list.length?list.map(e=>`<div class="diagV2Event ${e.severity}"><time>${esc(e.time)}</time><b>${esc(e.type)}</b><span>${esc(e.message)}</span></div>`).join(''):'<div class="diagV2Empty"><small>No matching diagnostic events yet.</small></div>'}
function trendTiles(items){return `<div class="diagV2Trends context">${items.map(x=>`<div class="diagV2Trend"><span>${x[0]}</span><b>${x[1]}</b>${spark(x[2],x[3])}</div>`).join('')}</div>`}
function testRows(){const rows=tests.length?tests:checks().map(x=>({...x,time:'—'}));return rows.map(x=>`<div class="diagV2Test ${x.kind}"><span class="icon">${x.kind==='ok'?'✓':x.kind==='warn'?'!':'×'}</span><span>${esc(x.name)}</span><b>${x.kind.toUpperCase()}</b><time>${esc(x.time||'—')}</time></div>`).join('')}
function bottomDefinition(){const s=stateRef(),tooth=trends.tooth.length?trends.tooth[trends.tooth.length-1]:0;switch(activeTool){
  case'faults':return{title:'EVENT HISTORY',meta:'LOCAL DIAGNOSTIC CHANGES',body:eventRows()};
  case'sensors':return{title:'LIVE SENSOR TRENDS',meta:`LAST ${diagTrendSeconds} s`,body:trendTiles([['Coolant',`${dPresent('temperature',s.clt).text} ${dPresent('temperature',s.clt).unit}`,trends.clt,'cyan'],['Mixture',`${dPresent('afr',s.afr).text} ${dPresent('afr',s.afr).unit}`,trends.afr,'green'],['Fuel ΔP',`${dPresent('pressureKpa',s.fuelDelta).text} ${dPresent('pressureKpa',s.fuelDelta).unit}`,trends.fuelDelta,'amber'],['Battery',`${dPresent('voltage',s.batt).text} ${dPresent('voltage',s.batt).unit}`,trends.batt,'cyan']])};
  case'trigger':return{title:'TRIGGER / SYNC TREND',meta:'LIVE BOUNDED HISTORY',body:trendTiles([['Engine speed',`${n(s.rpm,0)} rpm`,trends.rpm,'cyan'],['Sync errors',Number(s.syncOk)===0?'1':'0',trends.sync,Number(s.syncOk)===0?'red':'green'],['Tooth error',`${n(tooth,1)} %`,trends.tooth,tooth>7.5?'amber':'cyan']])};
  case'power':return{title:'DISPLAY CHECK RESULTS',meta:'READ ONLY',body:`<div class="diagV2ContextTests">${testRows()}</div>`};
  case'communications':case'network':return{title:'COMMUNICATION EVENT HISTORY',meta:'LOCAL',body:eventRows(e=>e.type==='COMM'||e.type==='INFO'||e.type==='EXPORT')};
  default:return null;
}}
function renderContextBottom(){const page=document.querySelector('.diagnosticsPageV2'),box=document.getElementById('diagV2Bottom'),rail=document.getElementById('diagV2BottomRevealRail'),def=bottomDefinition();if(!page||!box||!rail)return;if(!def){page.classList.add('noContextBottom');page.classList.remove('hideBottom');box.innerHTML='';return}const phone=diagPhoneMode();if(phone)bottomVisible=true;page.classList.remove('noContextBottom');page.classList.toggle('hideBottom',!phone&&!bottomVisible);box.innerHTML=`${phone?'':`<button class="diagBottomFoldHandle" data-diag-action="toggleBottom" title="Hide the complete lower diagnostics panel"><span>▼</span><b>HIDE BOTTOM PANEL</b><span>▼</span></button>`}<section class="pCard diagV2ContextCard"><div class="pCardTitle">${esc(def.title)} <span style="margin-left:auto" class="pMuted">${esc(def.meta)}</span></div><div class="diagV2ContextBody">${def.body}</div></section>`}
function runChecks(){tests=checks().map(x=>({...x,time:nowTime()}));addEvent('TEST','Read-only display diagnostics completed',tests.some(x=>x.kind==='bad')?'bad':tests.some(x=>x.kind==='warn')?'warn':'info');renderMain();renderContextBottom()}
function report(){return{format:'EpicDash UX diagnostics snapshot v2',createdAt:new Date().toISOString(),readOnly:true,app:(()=>{try{return appDiagnosticsObject()}catch(_){return {}}})(),connection:connectionState(),runtime:{...stateRef()},faults:faults(),sensors:sensorRows(),checks:checks(),events:events.slice(),native:nativeCache}}
function copyReport(){const text=JSON.stringify(report(),null,2);try{window.EpicDashAndroid?.copyText?.('EpicDash UX diagnostics report',text)}catch(_){navigator.clipboard?.writeText(text)}addEvent('EXPORT','Diagnostics report copied','info');renderContextBottom()}
function template(){return `<div class="diagnosticsPageV2"><aside class="pCard diagV2Sidebar"><div class="pCardTitle">DIAGNOSTICS TOOLS <span style="margin-left:auto" class="pGreen">READ ONLY</span></div><input id="diagV2Search" class="diagV2Search" type="search" placeholder="Search diagnostics…"><div class="diagV2Nav" id="diagV2Nav"></div><div class="diagV2SidebarActions"><button class="pButton active" data-diag-action="refresh">REFRESH</button><button class="pButton" data-diag-action="copyReport">COPY REPORT</button><button class="pButton" data-diag-action="runChecks">RUN CHECKS</button><button class="pButton red" data-diag-action="clearEvents">CLEAR EVENTS</button><div class="diagV2SidebarNote">Clear affects only the local app event list. ECU fault clearing is not available.</div></div></aside><div class="diagV2Summary" id="diagV2Summary"></div><section class="pCard diagV2Main" id="diagV2Main"></section><div class="diagV2Bottom" id="diagV2Bottom"></div><button class="diagBottomRevealRail" id="diagV2BottomRevealRail" data-diag-action="toggleBottom" aria-label="Display hidden contextual diagnostics panel"><span>▲</span><b>SHOW BOTTOM PANEL</b><span>▲</span></button></div>`}
function diagRequestReflow(){requestAnimationFrame(()=>requestAnimationFrame(()=>{try{renderMain();window.dispatchEvent(new Event('resize'))}catch(_){}}))}
function applyBottomLayout(){const page=document.querySelector('.diagnosticsPageV2');if(!page)return;const has=!!bottomDefinition(),phone=diagPhoneMode();if(phone)bottomVisible=true;page.classList.toggle('noContextBottom',!has);page.classList.toggle('hideBottom',has&&!phone&&!bottomVisible);diagRequestReflow()}
function init(){loadPrefs();try{const all=window.SettingsUX?.getConfig?.()||{},m=all.diagnostics?.triggerMode;if(['crank','cam','combo'].includes(m))triggerTab=m;diagTrendSeconds=Number(all.diagnostics?.trendSeconds)||60;diagVerbosity=all.diagnostics?.verbosity||'normal';diagRawValues=!!all.units?.rawValues}catch(_){}nativeCache=nativeDiagnostics();const diagPage=document.querySelector('.diagnosticsPageV2');if(diagPage)diagPage.dataset.verbosity=diagVerbosity;if(!events.length)addEvent('INFO','Diagnostics session started','info');renderNav();renderSummary();renderMain();renderContextBottom();applyBottomLayout();const input=document.getElementById('diagV2Search');if(input){input.value=search;input.oninput=e=>{search=e.target.value;renderNav()}}if(bound)return;bound=true;const panel=document.getElementById('panelContent');panel.addEventListener('contextmenu',e=>{if(e.target?.closest?.('[data-diag-action],button,.pButton')&&!e.target?.closest?.('input,textarea,select'))e.preventDefault()});panel.addEventListener('selectstart',e=>{if(e.target?.closest?.('[data-diag-action],button,.pButton')&&!e.target?.closest?.('input,textarea,select'))e.preventDefault()});panel.addEventListener('click',e=>{const a=e.target?.closest?.('[data-diag-action]');if(!a)return;switch(a.dataset.diagAction){case'tool':activeTool=a.dataset.tool;renderNav();renderMain();renderContextBottom();applyBottomLayout();break;case'refresh':nativeCache=nativeDiagnostics();addEvent('INFO','Diagnostics refreshed','info');refresh(true);break;case'copyReport':copyReport();break;case'runChecks':runChecks();break;case'clearEvents':events=[];addEvent('INFO','Local diagnostic event history cleared','info');renderContextBottom();break;case'triggerTab':triggerTab=a.dataset.value;renderMain();break;case'toggleBottom':if(diagPhoneMode()){bottomVisible=true;applyBottomLayout();break}bottomVisible=!bottomVisible;savePrefs();applyBottomLayout();break}})}
function refresh(force=false){try{if(currentPage!=='diagnostics'&&!force)return}catch(_){if(!force)return}const now=performance.now();if(!force&&now-lastRefresh<180)return;lastRefresh=now;if(now-lastSample>450){lastSample=now;sampleTrends();checkFaultEvents();checkConnectionEvent()}renderSummary();renderNav();renderMain();renderContextBottom();applyBottomLayout()}
function diagnostics(){return{activeTool,triggerView:triggerTab,events:events.length,faults:faults().length,sensorChecks:sensorRows().length,trendSamples:trends.batt.length,bottomVisible,readOnly:true}}
function applyDiagnosticSettings(c={},raw=false){if(['crank','cam','combo'].includes(c.triggerMode))triggerTab=c.triggerMode;diagTrendSeconds=[30,60,120].includes(Number(c.trendSeconds))?Number(c.trendSeconds):60;bottomVisible=diagPhoneMode()?true:c.bottomVisible!==false;diagVerbosity=['compact','normal','verbose'].includes(c.verbosity)?c.verbosity:'normal';diagRawValues=!!raw;savePrefs();const page=document.querySelector('.diagnosticsPageV2');if(page){page.dataset.verbosity=diagVerbosity;renderNav();renderSummary();renderMain();renderContextBottom();applyBottomLayout()}}
window.addEventListener('epicdashux:viewportchange',()=>{if(diagPhoneMode())bottomVisible=true;if(document.querySelector('.diagnosticsPageV2')){renderContextBottom();applyBottomLayout()}});
window.DiagnosticsUX={template,init,refresh,applySettings:applyDiagnosticSettings,diagnostics,copyReport};
})();
