/* EpicDash UX r31 — persistent presentation units through live/no-signal transitions. */
(function(){
'use strict';
const KEY='epicdashUX.settings.v1',APP_KEY='epicdashUX.appPrefs.v1',BACKUP_KEY='epicdashUX.backupHistory.v1';
const defaults={
 connection:{autoConnect:true,pollHz:20,reconnect:true,reconnectDelay:2,transport:'usb'},
 display:{theme:'dark',accent:'cyan',brightness:100,density:'normal',keepAwake:true,reducedMotion:false},
 navigation:{swipeEnabled:true,swipeThreshold:90,dashboardButton:true},
 dashboard:{animations:true,demoRate:1,warningPopup:true,vibrate:false,rpmMajorStepsR29:false,gaugePrecision:{},gaugeLimits:{rpmDial:{min:0,max:9000},boostDial:{min:-1,max:2},afrDial:{min:9,max:20},cltDial:{min:40,max:120},oilDial:{min:0,max:10},fuelDial:{min:0,max:100}}},
 units:{temperature:'C',pressure:'metric',speed:'kmh',afr:'gas',precisionDigits:1,voltageDigits:1,rawValues:false},
 tables:{traceDefault:true,flipX:false,flipY:true,reverseDefaultRotationX:true,reverseDefaultRotationY:true,defaultZoom:100,confirmBulk:true,haptics:true},
 logging:{sampleRate:10,windowSec:20,markerChannels:true,autoMarkerWarnings:false,maxVisible:8,bufferSeconds:360,exportFormat:'both'},
 alerts:{enabled:true,coolantWarning:95,coolantCritical:105,oilWarning:1.2,oilCritical:.7,batteryLow:11.5,batteryHigh:15.2,boostWarning:1.4,afrLean:15.5,fuelDeltaLow:200,knockHigh:3},
 diagnostics:{triggerMode:'combo',trendSeconds:60,bottomVisible:true,verbosity:'normal'},
 storage:{autosaveDraft:true,backupCount:10}
};
const clone=x=>JSON.parse(JSON.stringify(x));
let cfg=clone(defaults),active='connection',query='',boundPanel=null,toastTimer=0,modalMode='export',applyBusy=false;
const categories=[
 ['connection','◉','Connection & ECU','USB source, poll rate and reconnect'],
 ['display','▤','Display & navigation','Theme, brightness and gestures'],
 ['dashboard','◎','Dashboard & demo','Animation, demo and warning behavior'],
 ['units','△','Units & presentation','AFR, pressure and display precision'],
 ['tables','▦','Tables','Axes, trace and editing defaults'],
 ['logging','◌','Logging','Rate, graph window and marker export'],
 ['alerts','⚠','Alerts & safety','Display-only warning thresholds'],
 ['diagnostics','◇','Diagnostics','Trigger view, trends and detail level'],
 ['storage','⇄','Storage & reset','Backup, restore and local data']
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(path,obj=cfg)=>path.split('.').reduce((a,k)=>a?.[k],obj);
const set=(path,value,obj=cfg)=>{const p=path.split('.'),last=p.pop();let n=obj;for(const k of p)n=n[k]||(n[k]={});n[last]=value};
function merge(base,src){const out=clone(base);const walk=(a,b)=>{for(const [k,v] of Object.entries(b||{})){if(v&&typeof v==='object'&&!Array.isArray(v)&&a[k]&&typeof a[k]==='object')walk(a[k],v);else a[k]=v}};walk(out,src);return out}
function normalize(){
 cfg.connection.pollHz=Math.max(1,Math.min(50,Number(cfg.connection.pollHz)||20));cfg.connection.reconnectDelay=Math.max(1,Math.min(30,Number(cfg.connection.reconnectDelay)||2));
 cfg.display.theme=['dark','darker','oled','arctic','amber'].includes(cfg.display.theme)?cfg.display.theme:'dark';cfg.units.precisionDigits=Math.max(0,Math.min(3,Number.isFinite(Number(cfg.units.precisionDigits))?Number(cfg.units.precisionDigits):Number(cfg.units.voltageDigits)||1));cfg.units.voltageDigits=cfg.units.precisionDigits;cfg.display.brightness=Math.max(50,Math.min(120,Number(cfg.display.brightness)||100));cfg.navigation.swipeThreshold=Math.max(45,Math.min(180,Number(cfg.navigation.swipeThreshold)||90));
 cfg.tables.defaultZoom=Math.max(55,Math.min(180,Number(cfg.tables.defaultZoom)||100));for(const [k,d] of Object.entries(defaults.dashboard.gaugeLimits)){const g=cfg.dashboard.gaugeLimits[k]||d;g.min=Number.isFinite(Number(g.min))?Number(g.min):d.min;g.max=Number.isFinite(Number(g.max))?Number(g.max):d.max;if(g.max<=g.min)g.max=g.min+1;cfg.dashboard.gaugeLimits[k]=g}if(!cfg.dashboard.rpmMajorStepsR29){if(Number(cfg.dashboard.gaugeLimits.rpmDial?.max)===8000)cfg.dashboard.gaugeLimits.rpmDial.max=9000;cfg.dashboard.rpmMajorStepsR29=true}cfg.logging.sampleRate=Math.max(1,Math.min(50,Number(cfg.logging.sampleRate)||10));cfg.logging.maxVisible=Math.max(1,Math.min(8,Number(cfg.logging.maxVisible)||8));cfg.logging.bufferSeconds=Math.max(30,Math.min(1800,Number(cfg.logging.bufferSeconds)||360));
 cfg.alerts.coolantCritical=Math.max(Number(cfg.alerts.coolantWarning)||95,Number(cfg.alerts.coolantCritical)||105);cfg.alerts.oilCritical=Math.min(Number(cfg.alerts.oilWarning)||1.2,Number(cfg.alerts.oilCritical)||.7);cfg.alerts.batteryHigh=Math.max((Number(cfg.alerts.batteryLow)||11.5)+.1,Number(cfg.alerts.batteryHigh)||15.2);cfg.storage.backupCount=Math.max(1,Math.min(50,Number(cfg.storage.backupCount)||10));
}
function load(){let hasSettings=false;try{const raw=localStorage.getItem(KEY);hasSettings=!!raw;cfg=merge(defaults,JSON.parse(raw||'{}'))}catch(_){cfg=clone(defaults)};if(!hasSettings)try{const a=JSON.parse(localStorage.getItem(APP_KEY)||'{}');cfg.display.theme=a.theme||cfg.display.theme;cfg.display.keepAwake=a.keepAwake??cfg.display.keepAwake;cfg.display.reducedMotion=a.reducedMotion??cfg.display.reducedMotion;cfg.navigation.swipeEnabled=a.swipeEnabled??cfg.navigation.swipeEnabled;cfg.navigation.swipeThreshold=a.swipeThreshold??cfg.navigation.swipeThreshold}catch(_){}normalize()}
function persist(show=true){normalize();try{localStorage.setItem(KEY,JSON.stringify(cfg))}catch(_){}applyStored();if(show)toast('Settings applied and saved locally')}
function accentPair(name){return({cyan:['#00bdf4','#53d8ff'],green:['#82d600','#b7f04b'],amber:['#ff9800','#ffc45a'],ice:['#8edcff','#d6f5ff'],white:['#dce8ec','#ffffff']})[name]||['#00bdf4','#53d8ff']}
function precisionDigits(digits){const n=Number(digits);return Number.isFinite(n)&&n>=0?Math.max(0,Math.min(3,Math.round(n))):Math.max(0,Math.min(3,Number(cfg.units.precisionDigits)||0))}
function pressureUnit(kind){const mode=cfg.units.pressure;if(mode==='psi')return'psi';if(mode==='kpa')return'kPa';return kind==='kpa'?'kPa':'bar'}
function unitFor(kind){switch(kind){case'temperature':return cfg.units.temperature==='F'?'°F':'°C';case'speed':return cfg.units.speed==='mph'?'mph':'km/h';case'afr':return cfg.units.afr==='lambda'?'λ':'AFR';case'voltage':return'V';case'pressureKpa':return pressureUnit('kpa');case'pressureBar':return pressureUnit('bar');default:return''}}
function pressurePresent(value,kind,digits){const n=Number(value),mode=cfg.units.pressure,d=precisionDigits(digits),unit=pressureUnit(kind);if(!Number.isFinite(n))return{value:NaN,text:'—',unit};if(mode==='psi'){const psi=(kind==='kpa'?n/6.894757:n*14.5037738);return{value:psi,text:psi.toFixed(d),unit}}if(mode==='kpa'){const kpa=kind==='kpa'?n:n*100;return{value:kpa,text:kpa.toFixed(d),unit}}return kind==='kpa'?{value:n,text:n.toFixed(d),unit}:{value:n,text:n.toFixed(d),unit}}
function present(kind,value,digits){const n=Number(value),d=precisionDigits(digits);if(!Number.isFinite(n))return{value:NaN,text:'—',unit:unitFor(kind),raw:value};switch(kind){case'temperature':{const v=cfg.units.temperature==='F'?n*9/5+32:n;return{value:v,text:v.toFixed(d),unit:unitFor(kind),raw:n}}case'speed':{const v=cfg.units.speed==='mph'?n*.621371:n;return{value:v,text:v.toFixed(d),unit:unitFor(kind),raw:n}}case'afr':{if(cfg.units.afr==='lambda'){const v=n/14.7;return{value:v,text:v.toFixed(d),unit:unitFor(kind),raw:n}}return{value:n,text:n.toFixed(d),unit:unitFor(kind),raw:n}}case'voltage':return{value:n,text:n.toFixed(d),unit:unitFor(kind),raw:n};case'pressureKpa':return{...pressurePresent(n,'kpa',d),raw:n};case'pressureBar':return{...pressurePresent(n,'bar',d),raw:n};default:return{value:n,text:n.toFixed(d),unit:'',raw:n}}}
function toRaw(kind,value){const n=Number(value);if(!Number.isFinite(n))return NaN;switch(kind){case'temperature':return cfg.units.temperature==='F'?(n-32)*5/9:n;case'speed':return cfg.units.speed==='mph'?n/.621371:n;case'afr':return cfg.units.afr==='lambda'?n*14.7:n;case'pressureKpa':if(cfg.units.pressure==='psi')return n*6.894757;return n;case'pressureBar':if(cfg.units.pressure==='psi')return n/14.5037738;if(cfg.units.pressure==='kpa')return n/100;return n;default:return n}}
function applyStored(){if(applyBusy)return;applyBusy=true;load();
 try{if(typeof appPrefs!=='undefined'){appPrefs.theme=cfg.display.theme;appPrefs.keepAwake=!!cfg.display.keepAwake;appPrefs.reducedMotion=!!cfg.display.reducedMotion;appPrefs.swipeEnabled=!!cfg.navigation.swipeEnabled;appPrefs.swipeThreshold=Number(cfg.navigation.swipeThreshold)||90;try{localStorage.setItem(APP_KEY,JSON.stringify(appPrefs))}catch(_){}document.body.dataset.theme=appPrefs.theme;document.body.classList.toggle('reducedMotion',appPrefs.reducedMotion);document.body.classList.toggle('uxAnimationsOff',!cfg.dashboard.animations);window.EpicDashAndroid?.setKeepScreenAwake?.(appPrefs.keepAwake)}}catch(_){}
 const [a,b]=accentPair(cfg.display.accent);document.documentElement.style.setProperty('--cyan',a);document.documentElement.style.setProperty('--cyan2',b);document.documentElement.style.setProperty('--ux-brightness',String(Math.max(.45,Math.min(1.2,Number(cfg.display.brightness)/100||1))));document.body.dataset.uxDensity=cfg.display.density;
 try{const dashboardTab=document.querySelector('.tab[data-page="dashboard"]');if(dashboardTab)dashboardTab.style.display=cfg.navigation.dashboardButton?'':'none'}catch(_){}
 window.uxConnectionSettings={...cfg.connection};window.uxDemoRate=Number(cfg.dashboard.demoRate)||1;window.uxAutosaveDraft=!!cfg.storage.autosaveDraft;try{if(typeof tuneSaveDraft==='function')tuneSaveDraft()}catch(_){}
 try{localStorage.setItem('epicdashUX.tableTrace.v1',String(!!cfg.tables.traceDefault));localStorage.setItem('epicdashUX.tableAxis.v1',JSON.stringify({flipX:!!cfg.tables.flipX,flipY:!!cfg.tables.flipY}));window.TablesUX?.applySettings?.(clone(cfg.tables))}catch(_){}
 try{window.LoggingUX?.applySettings?.(clone(cfg.logging))}catch(_){}
 try{localStorage.setItem('epicdashUX.diagBottom.v1',String(!!cfg.diagnostics.bottomVisible));window.DiagnosticsUX?.applySettings?.(clone(cfg.diagnostics),!!cfg.units.rawValues)}catch(_){}
 try{if(cfg.connection.autoConnect){window.EpicDashAndroid?.setUsbPollHz?.(Number(cfg.connection.pollHz)||20);window.EpicDashAndroid?.setLiveTransport?.(cfg.connection.transport||'usb')}}catch(_){}
 try{window.ConceptRadialGauge?.rebuildAll?.();if(typeof render==='function')render();if(typeof renderWarningPopup==='function')renderWarningPopup()}catch(_){}
 applyBusy=false;
}
function warningConfig(){return{...cfg.alerts,popupEnabled:cfg.dashboard.warningPopup,vibrate:cfg.dashboard.vibrate,autoMarkerWarnings:cfg.logging.autoMarkerWarnings}}
function shouldAutosaveDraft(){return !!cfg.storage.autosaveDraft}
function shouldConfirmBulk(){return !!cfg.tables.confirmBulk}
function field(path,label,desc,type,opts={}){return{path,label,desc,type,...opts}}
const schemas={
 connection:[{title:'USB ECU communication',meta:'READ ONLY',items:[field('connection.transport','Preferred transport','Only USB is exposed in this standalone experiment.','select',{options:[['usb','USB OTG']]}),field('connection.autoConnect','Auto-connect','Attempt the selected read-only source when the app starts.','toggle'),field('connection.pollHz','Requested poll rate','Runtime request; the native bridge may cap the actual rate.','select',{options:[[10,'10 Hz'],[20,'20 Hz'],[30,'30 Hz'],[40,'40 Hz']]}),field('connection.reconnect','Automatic reconnect','Retry after a temporary USB disconnect.','toggle'),field('connection.reconnectDelay','Reconnect delay','Delay before the next local reconnect attempt.','number',{min:1,max:30,step:1,unit:'s'})]},{title:'Connection tools',meta:'NO ECU WRITES',items:[field('action.testConnection','Test diagnostic bridge','Reads the local/native diagnostics bridge and reports availability.','action',{text:'TEST CONNECTION'}),field('action.usbReconnect','Request USB reconnect','Asks the bridge to reconnect; no tune or configuration command is sent.','action',{text:'RECONNECT USB'}),field('info.policy','ECU access policy','The Layout Lab remains strictly read-only.','readonly',{value:'READ-ONLY • NO BURN / WRITE'})]}],
 display:[{title:'Theme & surface',meta:'APP ONLY',items:[field('display.theme','Theme','Applied immediately across the complete app.','segment',{options:[['dark','DEFAULT'],['oled','OLED'],['darker','STEEL'],['arctic','ARCTIC'],['amber','AMBER']]}),field('display.accent','Accent color','Primary telemetry and active-control color.','select',{options:[['cyan','Cyan'],['green','Green'],['amber','Amber'],['ice','Ice blue'],['white','White']]}),field('display.brightness','UI brightness','Software brightness multiplier; device brightness remains unchanged.','range',{min:50,max:120,step:5,unit:'%'}),field('display.density','Interface density','Compact reduces vertical spacing without shrinking primary values.','select',{options:[['normal','Normal'],['compact','Compact']]}),field('display.reducedMotion','Reduced motion','Disables decorative animation where supported.','toggle'),field('display.keepAwake','Keep screen awake','Requests Android to keep the display on while EpicDash UX is open.','toggle')]},{title:'Navigation',meta:'TOUCH',items:[field('navigation.swipeEnabled','Swipe between pages','Intent-aware page navigation: vertical motion scrolls; slow direct manipulation stays with tables, graphs, sliders and 3D views; a deliberate horizontal flick changes page.','toggle'),field('navigation.swipeThreshold','Swipe sensitivity','Lower distance reacts sooner; higher distance prevents accidental changes.','range',{min:45,max:180,step:5,unit:'px'}),field('navigation.dashboardButton','Dashboard navigation button','Keep the explicit Dashboard button in the main header.','toggle'),field('info.displayPreview','Preview','Current theme, accent and brightness preview.','preview')]}],
 dashboard:[{title:'Dashboard behavior',meta:'LIVE / DEMO',items:[field('dashboard.animations','Gauge animation','Animate dashboard gauges and state indicators.','toggle'),field('dashboard.demoRate','Demo scenario speed','Changes how quickly demo scenarios progress.','select',{options:[[.5,'0.5×'],[1,'1.0×'],[1.5,'1.5×'],[2,'2.0×']]}),field('dashboard.warningPopup','Warning acknowledgment popup','Display the read-only warning dialog until acknowledged.','toggle'),field('dashboard.vibrate','Vibrate on new warning','Uses device vibration when WebView permission/support is available.','toggle'),field('action.demoMenu','Open demo scenarios','Choose Idle, Cruise, Pull, Overrun, Hot or Fault.','action',{text:'OPEN DEMO MENU'})]},{title:'Gauge scale limits',meta:'DASHBOARD',items:[field('dashboard.gaugeLimits.rpmDial.min','RPM minimum','Lower scale limit for the RPM gauge.','number',{min:0,max:3000,step:100,unit:'rpm'}),field('dashboard.gaugeLimits.rpmDial.max','RPM maximum','Upper scale limit for the RPM gauge.','number',{min:1000,max:12000,step:100,unit:'rpm'}),field('dashboard.gaugeLimits.boostDial.min','Boost minimum','Lower boost/vacuum scale limit.','number',{min:-2,max:0,step:.1,unit:'bar'}),field('dashboard.gaugeLimits.boostDial.max','Boost maximum','Upper boost scale limit.','number',{min:.2,max:5,step:.1,unit:'bar'}),field('dashboard.gaugeLimits.afrDial.min','AFR minimum','Lower AFR Gas Scale limit.','number',{min:5,max:20,step:.1,unit:'AFR'}),field('dashboard.gaugeLimits.afrDial.max','AFR maximum','Upper AFR Gas Scale limit.','number',{min:10,max:30,step:.1,unit:'AFR'}),field('dashboard.gaugeLimits.cltDial.min','Coolant minimum','Lower coolant gauge scale.','number',{min:-40,max:100,step:1,unit:'°C'}),field('dashboard.gaugeLimits.cltDial.max','Coolant maximum','Upper coolant gauge scale.','number',{min:60,max:180,step:1,unit:'°C'}),field('dashboard.gaugeLimits.oilDial.min','Oil-pressure minimum','Lower oil-pressure gauge scale.','number',{min:0,max:5,step:.1,unit:'bar'}),field('dashboard.gaugeLimits.oilDial.max','Oil-pressure maximum','Upper oil-pressure gauge scale.','number',{min:2,max:20,step:.5,unit:'bar'}),field('dashboard.gaugeLimits.fuelDial.min','Fuel-level minimum','Lower fuel-level gauge scale.','number',{min:0,max:50,step:1,unit:'%'}),field('dashboard.gaugeLimits.fuelDial.max','Fuel-level maximum','Upper fuel-level scale.','number',{min:50,max:150,step:1,unit:'%'})]},{title:'Dashboard status',meta:'CURRENT',items:[field('info.demoState','Current demo state','Scenario and on/off state from the active dashboard session.','dynamic',{kind:'demo'}),field('info.warningState','Warning conditions','Current display-warning count based on configured thresholds.','dynamic',{kind:'warnings'}),field('info.dashboardSafety','Safety boundary','Warnings acknowledge display state only.','readonly',{value:'NO ECU CUT / OUTPUT COMMANDS'})]}],
 units:[{title:'Units & formats',meta:'PRESENTATION',items:[field('units.temperature','Temperature','Converts dashboard, logging and diagnostics temperature displays immediately.','select',{options:[['C','°C'],['F','°F']]}),field('units.pressure','Pressure','Metric keeps kPa for absolute pressure and bar for boost.','select',{options:[['metric','kPa / bar'],['kpa','kPa only'],['psi','psi']]}),field('units.speed','Vehicle speed','Converts dashboard, logging and diagnostics speed displays immediately.','select',{options:[['kmh','km/h'],['mph','mph']]}),field('units.afr','Mixture display','AFR Gas Scale remains the project default.','select',{options:[['gas','AFR Gas Scale'],['lambda','Lambda']]}),field('units.precisionDigits','Precision','Number of decimals used across relevant dashboard, logging and diagnostics values. Individual dashboard gauges may override this from their long-press menu.','select',{options:[[0,'0 decimals'],[1,'1 decimal'],[2,'2 decimals'],[3,'3 decimals']]}),field('units.rawValues','Show raw channels','Expose raw channel values in relevant diagnostic views.','toggle')]},{title:'Important conversion rule',meta:'TRANSPARENT',items:[field('info.conversion','Display conversion','Raw ECU values are not silently clamped, smoothed or rescaled.','readonly',{value:'EXPLICIT DISPLAY CONVERSIONS ONLY'}),field('info.afr','AFR rule','AFR views use the Gas Scale unless the user explicitly selects Lambda.','readonly',{value:'AFR GAS SCALE DEFAULT'})]}],
 tables:[{title:'Table viewport defaults',meta:'LOCAL DRAFT',items:[field('tables.traceDefault','2D live trace','Enable the single 2D live trace by default.','toggle'),field('tables.flipX','Reverse X axis','Present high X-axis values on the left. Tune-array order is unchanged.','toggle'),field('tables.flipY','Low load at bottom','Default presentation: low kPa at bottom and high kPa at top.','toggle'),field('tables.reverseDefaultRotationX','Reverse default X rotation','Reverse the initial/reset pitch of the 3D table without changing data or named view presets.','toggle'),field('tables.reverseDefaultRotationY','Reverse default Y rotation','Reverse the initial/reset yaw of the 3D table without changing data or named view presets.','toggle'),field('tables.defaultZoom','Default table zoom','Starting 2D table scale when opening the Tables page.','range',{min:55,max:180,step:5,unit:'%'}),field('tables.confirmBulk','Confirm broad edits','Ask before whole-table arithmetic or destructive local operations.','toggle'),field('tables.haptics','Table selection feedback','Use Android haptic feedback for cell and range selection.','toggle'),field('action.resetTableLayout','Reset panel layout','Restores left, right and bottom Tables panels.','action',{text:'RESET TABLE LAYOUT'})]},{title:'Table safety',meta:'READ ONLY ECU',items:[field('info.tableDraft','Editing destination','All operations modify only the local draft shared with Tuning.','readonly',{value:'LOCAL DRAFT'}),field('info.tableWrites','ECU write commands','Apply, burn and controller-memory writes are not implemented.','readonly',{value:'DISABLED'})]}],
 logging:[{title:'Local logging workspace',meta:'BOUNDED',items:[field('logging.sampleRate','Preview sample rate','Controls the current local acquisition/preview interval.','select',{options:[[5,'5 Hz'],[10,'10 Hz'],[20,'20 Hz']]}),field('logging.windowSec','Graph time window','Default visible graph history.','select',{options:[[10,'10 s'],[20,'20 s'],[30,'30 s'],[60,'60 s'],[120,'120 s']]}),field('logging.maxVisible','Maximum visible graphs','Limits simultaneous graph rendering.','select',{options:[[4,'4 graphs'],[6,'6 graphs'],[8,'8 graphs']]}),field('logging.bufferSeconds','Target local buffer','Sets the active in-memory ring-buffer duration.','select',{options:[[180,'3 min'],[360,'6 min'],[600,'10 min']]}),field('logging.markerChannels','Export marker channels','Include MarkerCode and MarkerIndex in CSV/MSL-style export.','toggle'),field('logging.autoMarkerWarnings','Mark warning events','Add a local marker when a new warning is displayed.','toggle'),field('logging.exportFormat','Preferred export','Controls which copy/export actions are shown on Logging.','select',{options:[['both','MSL + CSV'],['msl','MSL'],['csv','CSV']]})]},{title:'Logging status',meta:'CURRENT LIMITS',items:[field('info.loggingLimit','Current implementation','Bounded local preview; file-safe native logging is not yet included.','readonly',{value:'3,600 SAMPLES • 8 GRAPHS'}),field('action.openLogging','Open Logging page','Review the current functional logging workflow.','action',{text:'OPEN LOGGING'})]}],
 alerts:[{title:'Warning system',meta:'DISPLAY ONLY',items:[field('alerts.enabled','Enable warning evaluation','Turns all app-side warning checks on or off.','toggle'),field('alerts.coolantWarning','Coolant warning','Initial high-temperature warning threshold.','number',{min:60,max:130,step:1,unit:'°C'}),field('alerts.coolantCritical','Coolant critical','Critical acknowledgment threshold.','number',{min:70,max:140,step:1,unit:'°C'}),field('alerts.oilWarning','Oil-pressure warning','Running-engine display warning.','number',{min:0,max:10,step:.1,unit:'bar'}),field('alerts.oilCritical','Oil-pressure critical','Running-engine critical threshold.','number',{min:0,max:10,step:.1,unit:'bar'}),field('alerts.boostWarning','Boost warning','Gauge-pressure warning relative to barometric pressure.','number',{min:0,max:3,step:.05,unit:'bar'})]},{title:'Fuel, mixture & electrical',meta:'DISPLAY ONLY',items:[field('alerts.afrLean','Lean-under-load AFR','Evaluated only under load and throttle.','number',{min:9,max:22,step:.1,unit:'AFR'}),field('alerts.fuelDeltaLow','Fuel ΔP low','Differential fuel-pressure warning.','number',{min:0,max:600,step:10,unit:'kPa'}),field('alerts.knockHigh','Knock-retard warning','Display warning threshold.','number',{min:0,max:20,step:.5,unit:'°'}),field('alerts.batteryLow','Low system voltage','Lower critical voltage threshold.','number',{min:8,max:15,step:.1,unit:'V'}),field('alerts.batteryHigh','High system voltage','Upper critical voltage threshold.','number',{min:12,max:20,step:.1,unit:'V'}),field('action.testWarning','Test warning popup','Displays a local test warning without changing ECU state.','action',{text:'TEST WARNING'})]}],
 diagnostics:[{title:'Diagnostics presentation',meta:'READ ONLY',items:[field('diagnostics.triggerMode','Default trigger view','Crank, cam or combined view when opening Trigger / Sync.','select',{options:[['crank','Crank'],['cam','Cam'],['combo','Crank + Cam']]}),field('diagnostics.trendSeconds','Trend time span','Target bounded history presented in diagnostic trends.','select',{options:[[30,'30 s'],[60,'60 s'],[120,'120 s']]}),field('diagnostics.bottomVisible','Tablet context panel visible','Default state of the contextual diagnostics bottom panel on tablets. Phone layouts always keep contextual content visible.','toggle'),field('diagnostics.verbosity','Diagnostic detail','Controls app-side descriptive detail, not ECU fault reporting.','select',{options:[['compact','Compact'],['normal','Normal'],['verbose','Verbose']]}),field('action.openDiagnostics','Open Diagnostics page','Jump directly to the diagnostic workspace.','action',{text:'OPEN DIAGNOSTICS'}),field('action.copyDiagnostics','Copy app diagnostics','Copies an app/runtime diagnostic snapshot.','action',{text:'COPY DIAGNOSTICS'})]},{title:'Trigger rendering',meta:'VISUALIZATION',items:[field('info.triggerSource','Signal source','Current waveform is RPM/sync-derived until raw tooth events are available.','readonly',{value:'DERIVED VISUALIZATION'}),field('info.triggerStyle','Crank representation','Crank and cam are rendered as animated digital on/off square waves.','readonly',{value:'SQUARE WAVES'})]}],
 storage:[{title:'Export & restore',meta:'LOCAL APP DATA',items:[field('storage.autosaveDraft','Auto-save local tune draft','Keep local tune/table edits after app restart.','toggle'),field('storage.backupCount','Preferred backup count','Maximum number of rolling local UX snapshots retained.','number',{min:1,max:50,step:1,unit:'files'}),field('action.exportSettings','Export settings JSON','Copies only EpicDash UX settings.','action',{text:'COPY SETTINGS'}),field('action.exportAll','Backup all local UX data','Creates a rolling local snapshot and copies all EpicDash UX local data.','action',{text:'COPY FULL BACKUP'}),field('action.createSnapshot','Create local snapshot','Stores a restorable rolling snapshot inside EpicDash UX.','action',{text:'CREATE SNAPSHOT'}),field('action.restoreSnapshot','Restore latest snapshot','Restores the newest rolling local snapshot.','action',{text:'RESTORE LATEST'}),field('action.importSettings','Restore from JSON','Paste settings or a full local backup.','action',{text:'RESTORE JSON'}),field('action.copyStorage','Copy storage report','Lists local keys and approximate storage usage.','action',{text:'COPY STORAGE REPORT'})]},{title:'Reset tools',meta:'CAUTION',items:[field('action.resetCategory','Reset current category','Returns the active settings category to r27 defaults.','action',{text:'RESET THIS CATEGORY',className:'amber'}),field('action.resetWorkspaces','Reset workspace layouts','Restores panel positions, axes, zoom and logging window preferences.','action',{text:'RESET WORKSPACES',className:'amber'}),field('action.resetSettings','Reset app settings','Resets settings but keeps local tune draft and favorites.','action',{text:'RESET APP SETTINGS',className:'red'}),field('action.resetAll','Erase all EpicDash UX local data','Deletes draft, favorites, markers/preferences and settings. Official EpicDash JZ is untouched.','action',{text:'ERASE UX LOCAL DATA',className:'red'})]}]
};
function template(){return `<div class="settingsPageV2"><aside class="pCard settingsSideV2"><div class="pCardTitle">APP SETTINGS <span style="margin-left:auto" class="pGreen">LOCAL</span></div><input id="settingsSearchV2" class="settingsSearchV2" type="search" placeholder="Search settings…"><div class="settingsNavV2" id="settingsNavV2"></div><div class="settingsSideFootV2"><b>EpicDash UX 0.12.29-ux-state-31</b>Standalone experiment • package com.buttonbox.ble.ul<br>Settings never write to the ECU.</div></aside><section class="pCard settingsWorkspaceV2"><header class="settingsHeadV2"><div><h2 id="settingsTitleV2">SETTINGS</h2><small id="settingsSubtitleV2">Local application behavior</small></div><span class="spacer"></span><span class="settingsHeadStatusV2" id="settingsSaveStateV2">LOCAL SETTINGS ACTIVE</span><button class="pButton" data-settings-action="resetCategory">RESET CATEGORY</button></header><div class="settingsBodyV2" id="settingsBodyV2"></div><footer class="settingsFootV2">Scope: <b>EpicDash UX only</b><span class="spacer"></span><span id="settingsStorageV2"></span></footer></section><div class="settingsToastV2" id="settingsToastV2"></div><div class="settingsModalV2 hidden" id="settingsModalV2"><div class="settingsModalBoxV2"><div class="settingsModalHeadV2"><b id="settingsModalTitleV2">SETTINGS JSON</b><small id="settingsModalHintV2"></small><button data-settings-action="closeModal">×</button></div><div class="settingsModalBodyV2"><textarea id="settingsModalTextV2" spellcheck="false"></textarea></div><div class="settingsModalFootV2"><button class="pButton" data-settings-action="copyModal">COPY TEXT</button><span class="spacer"></span><button class="pButton" data-settings-action="closeModal">CANCEL</button><button class="pButton active" id="settingsModalApplyV2" data-settings-action="applyModal">APPLY RESTORE</button></div></div></div></div>`}
function nav(){const box=document.getElementById('settingsNavV2');if(!box)return;box.innerHTML=categories.map(c=>{const hits=countMatches(c[0]);return `<div class="settingsNavItemV2 ${active===c[0]?'active':''}" data-settings-action="category" data-category="${c[0]}"><span class="settingsNavIconV2">${c[1]}</span><span><strong>${esc(c[2])}</strong><small>${esc(c[3])}</small></span>${query&&hits?`<span class="settingsNavBadgeV2">${hits}</span>`:''}</div>`}).join('')}
function countMatches(cat){const q=query.trim().toLowerCase();if(!q)return 0;return (schemas[cat]||[]).flatMap(g=>g.items).filter(i=>`${i.label} ${i.desc} ${i.path}`.toLowerCase().includes(q)).length}
function control(i){const v=get(i.path);if(i.type==='toggle')return `<button class="settingToggleV2 ${v?'on':''}" data-settings-action="toggle" data-path="${i.path}" aria-label="${esc(i.label)}"></button>`;if(i.type==='select')return `<select data-settings-action="value" data-path="${i.path}">${i.options.map(o=>`<option value="${esc(o[0])}" ${String(v)===String(o[0])?'selected':''}>${esc(o[1])}</option>`).join('')}</select>`;if(i.type==='number')return `<input type="number" data-settings-action="value" data-value-type="number" data-path="${i.path}" value="${esc(v)}" min="${i.min}" max="${i.max}" step="${i.step}"><span class="settingRangeValueV2">${esc(i.unit||'')}</span>`;if(i.type==='range')return `<input type="range" data-settings-action="range" data-path="${i.path}" value="${esc(v)}" min="${i.min}" max="${i.max}" step="${i.step}"><span class="settingRangeValueV2" data-range-output="${i.path}">${esc(v)} ${esc(i.unit||'')}</span>`;if(i.type==='segment')return `<div class="settingSegmentV2">${i.options.map(o=>`<button data-settings-action="segment" data-path="${i.path}" data-value="${esc(o[0])}" class="${String(v)===String(o[0])?'active':''}">${esc(o[1])}</button>`).join('')}</div>`;if(i.type==='action')return `<button class="settingActionV2 ${i.className||''}" data-settings-action="run" data-run="${i.path.split('.').pop()}">${esc(i.text)}</button>`;if(i.type==='readonly')return `<div class="settingsReadOnlyV2">${esc(i.value)}</div>`;if(i.type==='preview')return `<div class="settingsPreviewV2"><div class="settingsPreviewDialV2"></div><div class="settingsPreviewMetricsV2"><b>1.12 bar</b><small>BOOST • ACCENT PREVIEW</small><b>82 °C</b><small>COOLANT • NORMAL</small></div></div>`;if(i.type==='dynamic'){let text='—';if(i.kind==='demo'){try{text=`${demo?'ON':'OFF'} • ${String(demoScenario||'idle').toUpperCase()}`}catch(_){}}if(i.kind==='warnings'){try{text=`${activeWarnings().length} ACTIVE`}catch(_){text='0 ACTIVE'}}return `<div class="settingsReadOnlyV2" data-dynamic="${i.kind}">${esc(text)}</div>`}return ''}
function render(){nav();const body=document.getElementById('settingsBodyV2');if(!body)return;const cat=categories.find(c=>c[0]===active)||categories[0],q=query.trim().toLowerCase();document.getElementById('settingsTitleV2').textContent=q?'SEARCH RESULTS':cat[2].toUpperCase();document.getElementById('settingsSubtitleV2').textContent=q?`Matching “${query}”`:cat[3];let groups=q?categories.flatMap(c=>(schemas[c[0]]||[]).map(g=>({...g,category:c[2],items:g.items.filter(i=>`${i.label} ${i.desc} ${i.path}`.toLowerCase().includes(q))}))).filter(g=>g.items.length):(schemas[active]||[]);body.innerHTML=`<div class="settingsSectionV2 ${q?'searchResults':''}">${groups.map(g=>`<section class="pCard settingsGroupV2"><div class="settingsGroupHeadV2"><b>${q?`${esc(g.category)} • `:''}${esc(g.title)}</b><span>${esc(g.meta||'')}</span></div><div class="settingsGroupBodyV2">${g.items.map(i=>`<div class="settingRowV2"><div class="settingLabelV2"><b>${esc(i.label)}</b><small>${esc(i.desc)}</small></div><div class="settingControlV2">${control(i)}</div></div>`).join('')}</div></section>`).join('')||'<div class="settingsNoteV2">No settings match this search.</div>'}</div>`;storageStatus()}
function storageStatus(){let bytes=0,count=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('epicdashUX.')){count++;bytes+=k.length+(localStorage.getItem(k)||'').length}}}catch(_){}const n=document.getElementById('settingsStorageV2');if(n)n.textContent=`${count} UX keys • ≈ ${(bytes/1024).toFixed(1)} KiB • ${backupHistory().length}/${cfg.storage.backupCount} snapshots • draft autosave ${cfg.storage.autosaveDraft?'ON':'OFF'}`}
function toast(msg,bad=false){const n=document.getElementById('settingsToastV2');if(!n)return;n.textContent=msg;n.classList.toggle('bad',bad);n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),2200)}
function setPath(path,value){set(path,value);normalize();persist(false);render();toast(`${path.split('.').pop()} applied`)}
function fullBackup(){const data={format:'EpicDash UX local backup v2',createdAt:new Date().toISOString(),package:'com.buttonbox.ble.ul',version:'0.12.29-ux-state-31',readOnlyEcu:true,localStorage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('epicdashUX.')&&k!==BACKUP_KEY)data.localStorage[k]=localStorage.getItem(k)}return data}
function backupHistory(){try{const x=JSON.parse(localStorage.getItem(BACKUP_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return []}}
function saveSnapshot(reason='manual'){const item={reason,createdAt:new Date().toISOString(),data:fullBackup()},list=backupHistory();list.push(item);const keep=Math.max(1,Number(cfg.storage.backupCount)||10);while(list.length>keep)list.shift();try{localStorage.setItem(BACKUP_KEY,JSON.stringify(list))}catch(_){}return item}
function restoreLatestSnapshot(){const list=backupHistory(),item=list[list.length-1];if(!item){toast('No local snapshot exists',true);return}if(!confirm(`Restore snapshot from ${new Date(item.createdAt).toLocaleString()}?`))return;for(const [k,v] of Object.entries(item.data.localStorage||{}))if(k.startsWith('epicdashUX.'))localStorage.setItem(k,String(v));load();applyStored();render();toast('Latest local snapshot restored')}
function showModal(mode,text){modalMode=mode;const m=document.getElementById('settingsModalV2');m.classList.remove('hidden');document.getElementById('settingsModalTitleV2').textContent=mode==='restore'?'RESTORE EPICDASH UX JSON':mode==='backup'?'FULL LOCAL BACKUP':'APP SETTINGS JSON';document.getElementById('settingsModalHintV2').textContent=mode==='restore'?'Paste exported settings or a full UX backup':'Copy and store this text safely';document.getElementById('settingsModalTextV2').value=text||'';document.getElementById('settingsModalApplyV2').style.display=mode==='restore'?'':'none'}
function copyText(label,text){try{window.EpicDashAndroid?.copyText?.(label,text);toast(`${label} copied`)}catch(_){navigator.clipboard?.writeText(text);toast(`${label} copied`)}}
function run(name){switch(name){
 case'testConnection':{let d={};try{d=JSON.parse(window.EpicDashAndroid?.getDiagnosticsJson?.()||'{}')}catch(_){}toast(d.app||d.nativeTransportIncluded!==undefined?'Diagnostic bridge responded':'No diagnostic bridge response',!Object.keys(d).length);break}
 case'usbReconnect':{let ok=false;try{window.EpicDashAndroid?.setUsbPollHz?.(Number(cfg.connection.pollHz)||20);window.EpicDashAndroid?.setLiveTransport?.(cfg.connection.transport||'usb');ok=!!window.EpicDashAndroid?.usbReconnect?.()}catch(_){}toast(ok?'USB reconnect requested':'Native USB reconnect unavailable in this build',!ok);break}
 case'demoMenu':try{openDemoScenarios()}catch(_){}break;
 case'resetTableLayout':try{window.TablesUX?.resetLayout?.()}catch(_){}localStorage.removeItem('epicdashUX.tableLayout.v1');toast('Tables panel layout reset');break;
 case'openLogging':try{navigateToPage('logging')}catch(_){}break;
 case'testWarning':try{warningNativeNotice='Settings test warning — display only';warningAcknowledgedKey='';renderWarningPopup()}catch(_){}break;
 case'openDiagnostics':try{navigateToPage('diagnostics')}catch(_){}break;
 case'copyDiagnostics':{let d={};try{d=appDiagnosticsObject()}catch(_){}copyText('EpicDash UX app diagnostics',JSON.stringify(d,null,2));break}
 case'exportSettings':showModal('settings',JSON.stringify({format:'EpicDash UX settings v2',settings:cfg},null,2));break;
 case'exportAll':{saveSnapshot('full backup export');showModal('backup',JSON.stringify(fullBackup(),null,2));break}
 case'createSnapshot':saveSnapshot('manual');toast(`Local snapshot saved (${backupHistory().length}/${cfg.storage.backupCount})`);storageStatus();break;
 case'restoreSnapshot':restoreLatestSnapshot();break;
 case'importSettings':showModal('restore','');break;
 case'copyStorage':{const b=fullBackup(),history=backupHistory(),report={createdAt:b.createdAt,keys:Object.entries(b.localStorage).map(([k,v])=>({key:k,chars:(v||'').length})),snapshots:history.map(x=>({createdAt:x.createdAt,reason:x.reason})),approxChars:Object.values(b.localStorage).reduce((a,v)=>a+(v||'').length,0)};copyText('EpicDash UX storage report',JSON.stringify(report,null,2));break}
 case'resetCategory':resetCategory();break;
 case'resetWorkspaces':if(confirm('Reset Tables, Logging and Diagnostics workspace presentation?')){saveSnapshot('before workspace reset');['epicdashUX.tableLayout.v1','epicdashUX.tableAxis.v1','epicdashUX.tableTrace.v1','epicdashUX.loggingPrefs.v1','epicdashUX.diagBottom.v1'].forEach(k=>localStorage.removeItem(k));cfg.tables=clone(defaults.tables);cfg.logging=clone(defaults.logging);cfg.diagnostics=clone(defaults.diagnostics);persist();render()}break;
 case'resetSettings':if(confirm('Reset EpicDash UX app settings while keeping tune draft, Quick Tuning and favorites?')){saveSnapshot('before settings reset');cfg=clone(defaults);localStorage.removeItem(KEY);persist();render()}break;
 case'resetAll':if(confirm('Erase ALL local EpicDash UX data? This does not affect EpicDash JZ or the ECU.')){saveSnapshot('before complete reset');const history=localStorage.getItem(BACKUP_KEY),keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('epicdashUX.'))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));if(history)localStorage.setItem(BACKUP_KEY,history);cfg=clone(defaults);persist(false);render();toast('All EpicDash UX local data erased; safety snapshot retained')}break;
}}
function resetCategory(){if(!confirm(`Reset ${active} settings to defaults?`))return;cfg[active]=clone(defaults[active]);persist();render()}
function applyRestore(){saveSnapshot('before JSON restore');const text=document.getElementById('settingsModalTextV2').value.trim();if(!text){toast('Paste JSON first',true);return}try{const d=JSON.parse(text);if(d.localStorage&&typeof d.localStorage==='object'){for(const [k,v] of Object.entries(d.localStorage))if(k.startsWith('epicdashUX.'))localStorage.setItem(k,String(v));load();applyStored()}else if(d.settings){cfg=merge(defaults,d.settings);persist(false)}else{cfg=merge(defaults,d);persist(false)}document.getElementById('settingsModalV2').classList.add('hidden');render();toast('EpicDash UX data restored')}catch(e){toast(`Invalid JSON: ${e.message}`,true)}}
function bind(){const panel=document.getElementById('panelContent');if(!panel||boundPanel===panel)return;boundPanel=panel;panel.addEventListener('contextmenu',e=>{if(e.target?.closest?.('[data-settings-action],button,.settingToggleV2')&&!e.target?.closest?.('input,textarea,select'))e.preventDefault()});panel.addEventListener('selectstart',e=>{if(e.target?.closest?.('[data-settings-action],button,.settingToggleV2')&&!e.target?.closest?.('input,textarea,select'))e.preventDefault()});panel.addEventListener('click',e=>{const a=e.target?.closest?.('[data-settings-action]');if(!a)return;const act=a.dataset.settingsAction;if(act==='category'){active=a.dataset.category;query='';const s=document.getElementById('settingsSearchV2');if(s)s.value='';render()}else if(act==='toggle')setPath(a.dataset.path,!get(a.dataset.path));else if(act==='segment')setPath(a.dataset.path,isNaN(Number(a.dataset.value))?a.dataset.value:Number(a.dataset.value));else if(act==='run')run(a.dataset.run);else if(act==='resetCategory')resetCategory();else if(act==='closeModal')document.getElementById('settingsModalV2').classList.add('hidden');else if(act==='copyModal')copyText('EpicDash UX JSON',document.getElementById('settingsModalTextV2').value);else if(act==='applyModal')applyRestore()});panel.addEventListener('change',e=>{const a=e.target?.closest?.('[data-settings-action="value"]');if(!a)return;let v=a.value;const base=get(a.dataset.path,defaults);if(a.dataset.valueType==='number'||typeof base==='number')v=Number(v);setPath(a.dataset.path,v)});panel.addEventListener('input',e=>{const a=e.target?.closest?.('[data-settings-action="range"]');if(a){const out=document.querySelector(`[data-range-output="${a.dataset.path}"]`);if(out){const schema=Object.values(schemas).flatMap(x=>x.flatMap(g=>g.items)).find(i=>i.path===a.dataset.path);out.textContent=`${a.value} ${schema?.unit||''}`}set(a.dataset.path,Number(a.value));persist(false)}})}
function init(){load();applyStored();bind();const s=document.getElementById('settingsSearchV2');if(s){s.value=query;s.oninput=e=>{query=e.target.value;render()}}render()}
function refresh(){if(typeof currentPage!=='undefined'&&currentPage!=='settings')return;document.querySelectorAll('[data-dynamic="demo"]').forEach(n=>{try{n.textContent=`${demo?'ON':'OFF'} • ${String(demoScenario||'idle').toUpperCase()}`}catch(_){}});document.querySelectorAll('[data-dynamic="warnings"]').forEach(n=>{try{n.textContent=`${activeWarnings().length} ACTIVE`}catch(_){}});storageStatus()}
load();
window.SettingsUX={template,init,refresh,applyStored,warningConfig,present,toRaw,getConfig:()=>clone(cfg),setValues:values=>{for(const [path,value] of Object.entries(values||{}))set(path,value);normalize();persist(false);render()},openCategory:category=>{active=schemas[category]?category:'dashboard';query='';try{navigateToPage('settings')}catch(_){}setTimeout(render,0)},shouldAutosaveDraft,shouldConfirmBulk,saveSnapshot,syncFromAppPrefs:()=>{try{if(typeof appPrefs!=='undefined'){cfg.display.theme=appPrefs.theme||cfg.display.theme;cfg.display.keepAwake=appPrefs.keepAwake??cfg.display.keepAwake;cfg.display.reducedMotion=appPrefs.reducedMotion??cfg.display.reducedMotion;cfg.navigation.swipeEnabled=appPrefs.swipeEnabled??cfg.navigation.swipeEnabled;cfg.navigation.swipeThreshold=appPrefs.swipeThreshold??cfg.navigation.swipeThreshold;normalize();localStorage.setItem(KEY,JSON.stringify(cfg))}}catch(_){}applyStored();render()}};
})();
